export const propertyData = [
  {
    id: 1,
    title: "DLF Phase-1",
    location: "Sector 62, Noida",
    price: "₹80 Lacs",
    badrooms: "3",
    bathroom: "2",
    area: "1,200 sqft",
    image: "https://housing-images.n7net.in/01c16c28/898b8a05ec242e0b8153a496424d7006/v0/medium/3_bhk_independent_builder_floor-for-sale-greater_kailash-New+Delhi-hall.jpg",
    description: "This stunning 3 BHK builder floor is located in the prime area of DLF Phase-1. It offers a perfect blend of luxury, convenience, and comfort. The property is ideal for families or professionals seeking modern living.",
    lat: 52.4797,  
    long: -1.20259 
  },
  {
    id: 2,
    title: "2 BHK Flat in Cyber City",
    price: "₹60 Lacs",
    area: "900 sqft",
    city: "Gurgaon",
    locality: "Cyber City",
    location: "Cyber City, Gurgaon",
    badrooms: "7",
    bathroom: "5",
    image: "https://lh5.googleusercontent.com/p/AF1QipM3rR8a9jngJ0Ort2gZOfbrd9LvW9AgPkA7936i=w114-h114-n-k-no",
    description: "This stunning 3 BHK builder floor is located in the prime area of DLF Phase-1. It offers a perfect blend of luxury, convenience, and comfort. The property is ideal for families or professionals seeking modern living.",
    lat: 52.4797,  
    long: -1.90259 
  },
  {
    id: 3,
    title: "3 BHK Apartment in Sector 4",
    price: "₹90 Lacs",
    area: "1,300 sqft",
    city: "Noida",
    locality: "Sector 4",
    location: "noida 8",
    badrooms: "3",
    bathroom: "2",
    image: "https://via.placeholder.com/300",
    description: "Modern 3 BHK with spacious living area and balcony.",
    lat: 50.4797,  
    long: -1.20259 
  },
  {
    id: 4,
    title: "2 BHK Flat in Dwarka",
    price: "₹55 Lacs",
    area: "850 sqft",
    city: "Delhi",
    locality: "Dwarka",
    location: "noida 62",
    badrooms: "3",
    bathroom: "2",
    image: "https://via.placeholder.com/300",
    description: "Cozy 2 BHK flat with great connectivity to metro stations.",
 lat: 53.4797,  
    long: -1.20259 
  },
  {
    id: 5,
    title: "1 BHK Studio Apartment in Sector 37",
    price: "₹35 Lacs",
    area: "600 sqft",
    city: "Gurgaon",
    locality: "Sector 37",
    location: "noida 62",
    badrooms: "3",
    bathroom: "2",
    image: "https://via.placeholder.com/300",
    description: "Affordable studio apartment with basic amenities.",
    lat: 52.4797,  
    long: 1.20259 
  },
  {
    id: 6,
    title: "4 BHK Villa in South Delhi",
    price: "₹1.5 Crore",
    area: "2,000 sqft",
    location: "noida 62",
    badrooms: "3",
    bathroom: "2",
    city: "Delhi",
    locality: "South Delhi",
    image: "https://via.placeholder.com/300",
    description: "Luxurious 4 BHK villa with garden and swimming pool.",
 lat: 51.4797,  
    long: -4.20259 
  }
  // Add the rest of the properties here with lat/long values.
];
