export const propertyData = [
    {
      "id": 1,
      "title": "DLF Phase-1",
      "location":"Sector 62, Noida",
      "price": "₹80 Lacs",
      "badrooms":"3 Badrooms",
      "bathroom":"2 Bathroom",
      "area": "1,200 sqft",
      "image": "https://housing-images.n7net.in/01c16c28/898b8a05ec242e0b8153a496424d7006/v0/medium/3_bhk_independent_builder_floor-for-sale-greater_kailash-New+Delhi-hall.jpg",
      "description": "This stunning 3 BHK builder floor is located in the prime area of DLF Phase-1. It offers a perfect blend of luxury, convenience, and comfort. The property is ideal for families or professionals seeking modern living.."
    },
    {
      "id": 2,
      "title": "2 BHK Flat in Cyber City",
      "price": "₹60 Lacs",
      "area": "900 sqft",
      "city": "Gurgaon",
      "locality": "Cyber City",
      "location":"Cyber City, Gurgaon",
      "badrooms":"7 Badrooms",
      "bathroom":"5 Bathroom",
      "image": "https://lh5.googleusercontent.com/p/AF1QipM3rR8a9jngJ0Ort2gZOfbrd9LvW9AgPkA7936i=w114-h114-n-k-no",
      "description": "This stunning 3 BHK builder floor is located in the prime area of DLF Phase-1. It offers a perfect blend of luxury, convenience, and comfort. The property is ideal for families or professionals seeking modern living.."
    },
    {
      "id": 3,
      "title": "3 BHK Apartment in Sector 4",
      "price": "₹90 Lacs",
      "area": "1,300 sqft",
      "city": "Noida",
      "locality": "Sector 4",
      "location":"noida 8",
      "badrooms":"3",
      "bathroom":"2",
      "image": "https://via.placeholder.com/300",
      "description": "Modern 3 BHK with spacious living area and balcony."
    },
    {
      "id": 4,
      "title": "2 BHK Flat in Dwarka",
      "price": "₹55 Lacs",
      "area": "850 sqft",
      "city": "Delhi",
      "locality": "Dwarka",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "image": "https://via.placeholder.com/300",
      "description": "Cozy 2 BHK flat with great connectivity to metro stations."
    },
    {
      "id": 5,
      "title": "1 BHK Studio Apartment in Sector 37",
      "price": "₹35 Lacs",
      "area": "600 sqft",
      "city": "Gurgaon",
      "locality": "Sector 37",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "image": "https://via.placeholder.com/300",
      "description": "Affordable studio apartment with basic amenities."
    },
    {
      "id": 6,
      "title": "4 BHK Villa in South Delhi",
      "price": "₹1.5 Crore",
      "area": "2,000 sqft",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "city": "Delhi",
      "locality": "South Delhi",
      "image": "https://via.placeholder.com/300",
      "description": "Luxurious 4 BHK villa with garden and swimming pool."
    },
    {
      "id": 7,
      "title": "3 BHK Flat in Sector 85",
      "price": "₹75 Lacs",
      "area": "1,100 sqft",
      "city": "Noida",
      "locality": "Sector 85",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "image": "https://via.placeholder.com/300",
      "description": "Spacious and modern 3 BHK flat with excellent amenities."
    },
    {
      "id": 8,
      "title": "2 BHK Flat in Sector 14",
      "price": "₹45 Lacs",
      "area": "850 sqft",
      "city": "Gurgaon",
      "locality": "Sector 14",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "image": "https://via.placeholder.com/300",
      "description": "Well-maintained 2 BHK flat in a quiet locality."
    },
    {
      "id": 9,
      "title": "3 BHK Apartment in Sector 21",
      "price": "₹80 Lacs",
      "area": "1,250 sqft",
      "city": "Noida",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "locality": "Sector 21",
      "image": "https://via.placeholder.com/300",
      "description": "Comfortable 3 BHK apartment in a gated community."
    },
    {
      "id": 10,
      "title": "3 BHK Duplex in Noida Extension",
      "price": "₹1 Crore",
      "area": "1,500 sqft",
      "city": "Noida",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "locality": "Noida Extension",
      "image": "https://via.placeholder.com/300",
      "description": "Modern 3 BHK duplex with a large terrace and great views."
    },
    {
      "id": 11,
      "title": "1 BHK Flat in Rohini",
      "price": "₹40 Lacs",
      "area": "650 sqft",
      "city": "Delhi",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "locality": "Rohini",
      "image": "https://via.placeholder.com/300",
      "description": "Affordable 1 BHK flat in a bustling locality."
    },
    {
      "id": 12,
      "title": "4 BHK House in Gurgaon",
      "price": "₹1.2 Crore",
      "area": "2,400 sqft",
      "city": "Gurgaon",
      "locality": "Sector 56",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "image": "https://via.placeholder.com/300",
      "description": "Luxury 4 BHK house with a large garden and garage."
    },
    {
      "id": 13,
      "title": "2 BHK Apartment in Sushant Lok",
      "price": "₹50 Lacs",
      "area": "900 sqft",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "city": "Gurgaon",
      "locality": "Sushant Lok",
      "image": "https://via.placeholder.com/300",
      "description": "Affordable 2 BHK apartment with modern finishes."
    },
    {
      "id": 14,
      "title": "5 BHK Penthouse in Connaught Place",
      "price": "₹3 Crore",
      "area": "3,500 sqft",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "city": "Delhi",
      "locality": "Connaught Place",
      "image": "https://via.placeholder.com/300",
      "description": "Stunning 5 BHK penthouse with luxurious amenities."
    },
    {
      "id": 15,
      "title": "3 BHK Apartment in Saket",
      "price": "₹1 Crore",
      "area": "1,400 sqft",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "city": "Delhi",
      "locality": "Saket",
      "image": "https://via.placeholder.com/300",
      "description": "Spacious 3 BHK apartment in a prime location."
    },
    {
      "id": 16,
      "title": "2 BHK Flat in Sector 15",
      "price": "₹55 Lacs",
      "area": "950 sqft",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "city": "Gurgaon",
      "locality": "Sector 15",
      "image": "https://via.placeholder.com/300",
      "description": "Affordable 2 BHK flat in a gated community."
    },
    {
      "id": 17,
      "title": "3 BHK Villa in Sector 61",
      "price": "₹95 Lacs",
      "area": "1,600 sqft",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "city": "Noida",
      "locality": "Sector 61",
      "image": "https://via.placeholder.com/300",
      "description": "Luxury 3 BHK villa with a private garden."
    },
    {
      "id": 18,
      "title": "2 BHK Flat in Faridabad",
      "price": "₹40 Lacs",
      "area": "850 sqft",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "city": "Faridabad",
      "locality": "Sector 15",
      "image": "https://via.placeholder.com/300",
      "description": "Budget-friendly 2 BHK flat in a developing locality."
    },
    {
      "id": 19,
      "title": "3 BHK Apartment in Greater Noida",
      "price": "₹70 Lacs",
      "area": "1,200 sqft",
      "location":"noida 62",
      "badrooms":"3 Badrooms",
      "bathroom":"2 Bathroom",
      "city": "Greater Noida",
      "locality": "Tech Zone",
      "image": "https://housing-images.n7net.in/01c16c28/898b8a05ec242e0b8153a496424d7006/v0/medium/3_bhk_independent_builder_floor-for-sale-greater_kailash-New+Delhi-hall.jpg",
      "description": "Spacious 3 BHK apartment with easy access to highways."
    },
    {
      "id": 20,
      "title": "2 BHK Flat in Lajpat Nagar",
      "price": "₹65 Lacs",
      "area": "1,000 sqft",
      "city": "Delhi",
      "location":"noida 62",
      "badrooms":"3",
      "bathroom":"2",
      "locality": "Lajpat Nagar",
      "image": "https://via.placeholder.com/300",
      "description": "Well-maintained 2 BHK flat in a central location."
    }
  ];
  